collections:
  shows:
  songs:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      path: ''
    values:
      layout: default
  - scope:
      path: ''
      type: songs
    values:
      layout: song
      section: songs

exclude:
  - README.md
  - '**/README.md'

  # Jekyll defaults, which would otherwise get overridden.
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

theme: null

ja_weekdays: [日, 月, 火, 水, 木, 金, 土]
